services:
  backend:
    build: ./backend
    image: buses-backend-local:latest
    ports:
      - "8099:8099"
    volumes:
      - ./backend/data:/app/data
    environment:
      - JAVA_OPTS=-Xmx512m
      - USE_MONGO=true
    env_file:
      - ./backend/.env
    networks:
      - buses_network
  frontend:
    build: ./frontend
    image: buses-frontend-local:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - API_URL=http://backend:8099
      - FLASK_SECRET_KEY=QjRReXlVb1ZYWG1RNkF4bG1xS0xVSWJfV1R3cV9rM2pZcXJqWnNlVQ==
    volumes:
      - ./frontend:/app
      - ./backend/data:/app/data
    env_file:
      - ./backend/.env
    depends_on:
      - backend
    networks:
      - buses_network

networks:
  buses_network:
    driver: bridge
